spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_media
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  expireAt: 86400000
  secretKey: HHwuNoEmnzoM51UiM13kM1aUb4jBrkrPiINKGD4QjbW/C9F9MuwsHEfIPPVpxAUn