spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_media
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
#  liquibase:
#    change-log: classpath:/db/changelog/changelog-master.xml
#    database-change-log-table: social_media_log
#    database-change-log-lock-table: social_media_log_lock
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: myfriends.social.media@gmail.com
    password: dfabimeqojqfsxoj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expireAt: 86400000
  secretKey: HHwuNoEmnzoM51UiM13kM1aUb4jBrkrPiINKGD4QjbW/C9F9MuwsHEfIPPVpxAUn

server:
  port: 8086